version: "3.5"

services:
  api1: &api
    build: .
    container_name: api1
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    hostname: api1
    environment:
      - DB_POOL_SIZE=10
      - DB_HOSTNAME=postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - pgbouncer
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api2:
    <<: *api 
    hostname: api2
    container_name: api2
    environment:
      - DB_HOSTNAME=postgres
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "150MB"

  postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=sinatra
      - POSTGRES_USER=frank
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./config/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "100MB"

  pgbouncer:
    image: pgbouncer/pgbouncer
    hostname: pgbouncer
    container_name: pgbouncer
    environment:
      - DATABASES_HOST=postgres
      - DATABASES_PORT=5432
      - DATABASES_USER=frank
      - DATABASES_PASSWORD=sinatra
      - DATABASES_DBNAME=postgres
      - DATABASES_POOL_SIZE=100
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_RESERVE_POOL_SIZE=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=100
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100MB'

volumes:
  rubygems: